import type { Metadata } from "next";
import { Geist, Geist_Mono, Sigmar_One, Grape_Nuts } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistOi = Sigmar_One({
  variable: "--font-geist-so",
  weight: "400",
  subsets: ["latin"],
});

const grapeNuts = Grape_Nuts({
  variable: "--font-grape-nuts",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistOi.variable} ${grapeNuts.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
